### PR TITLE
make simplify helper functions directly available from the module root

### PR DESCRIPTION
**Pull request by maxlath**
to be able to import like this:
```js
import { simplifySparqlResults } from 'wikibase-sdk'
```
as an alternative to 
```js
import { simplify } from 'wikibase-sdk'
const { sparqlResults: simplifySparqlResults } = simplify
```

I think the `simplify` object remains useful for use-case relying on `simplify[attribute]` ([example](https://github.com/maxlath/wikibase-sdk/blob/cddcff7/src/helpers/simplify_entity.ts#L39)), so maybe it's fine to also keep it?

@EdJoPaTo @mshd what do you think?

### CODE REVIEW

**Review by mshd — APPROVED** [review]
Yeah, that's a great addition 😊

**Comment by EdJoPaTo** [comment]
This is nice and I would like to see every instance independent function be exported like that. 🙃

**Comment by EdJoPaTo** [comment]
Personally I wouldn’t add them to the Wbk interface. I think the Wbk interface is good for instance specific things but not for the instance indepent methods. In the long runs all of them should be removed there in my opinion but that’s breaking.

**Comment by maxlath** [comment]
> This is nice and I would like to see every instance independent function be exported like that. 

> Personally I wouldn’t add them to the Wbk interface. I think the Wbk interface is good for instance specific things but not for the instance indepent methods. In the long runs all of them should be removed there in my opinion but that’s breaking.

@EdJoPaTo I agree with both proposition, and would be fine with publishing a new major version with the breaking changes. I can't work on it this week, so if you're up for it, you can claim the task; otherwise I might do it in the coming weeks.

**Comment by EdJoPaTo** [comment]
@maxlath looks like everything is already exported directly. The breaking change is the removal of the `common` stuff in the `wikibase-sdk.ts`. That's easy and as I assume more breaking changes in order to simplify the typings especially for the simplify methods I think we should wait with another breaking change release.

https://github.com/maxlath/wikibase-sdk/blob/41841fa76efd999937b711bb36d7e821d160691f/src/wikibase-sdk.ts#L23-L29

**Pull request merged**
