### PR TITLE
Load Languages from Wikidata

### LINKED ISSUE #107: Entity Language Type is incorrect
- wikibase-sdk version: 9.0.5
- Environment: 19.7.0

Currently the Entity Type for labels, description, aliases and so on is `Record<WmLanguageCode, …>`. `WmLanguageCode` is only `de` but not something like `de-ch` which is also there.

Not sure how to model all the possible variations there or just to use `string` or `type LanguageCode = string` to help with code reading?

### PR DESCRIPTION
**Pull request by EdJoPaTo**
currently WmLanguageCode is based on the sites. I updated the scripts to load both the sites and the languages from Wikidata. As Wikidata probably knows all the languages from other Wikimedia projects it seems like a good source of languages for me.

I also changed some code related to languages and removed the `shortLang` method. The shortLang reduced the options usable for methods like getEntities as you couldn’t specify `de-ch` earlier as it was automatically reduced to `de`. This seems like a bug to me but I might miss something?

All the test cases still work except one which I think was a bug: `getSitelinkData().lang` included _ which only sites include. The language like it’s used in URLs and the lang arguments uses the -. The getSitelinkUrl also depends on it so I think this was another bug and the test case was also wrong.

Fixes #107 

Uses a helper from #106 so it should be merged first. Only the last commit is unique to this PR.

### CODE REVIEW

**Comment by EdJoPaTo** [comment]
[wikidata-lang](https://github.com/inventaire/wikidata-lang) provides way more language information. Not sure if wikibase-sdk should contain the basic Wikidata information too?

**Comment by maxlath** [comment]
> hm… maybe the type Language should be named LanguageCode as it doesn't represent a Language and rather a short language code to it.

+1 for `LanguageCode`

**Comment by maxlath** [comment]
Having a hard coded language shortlist was a nice to have from the time this lib was wikidata specific, but it doesn't provide that much value, from what I can gather: let's try `type LanguageCode = string`?

**Comment by EdJoPaTo** [comment]
superseded by #120

**Pull request closed without merging**
