### PR TITLE
feat: export types

### PR DESCRIPTION
**Pull request by EdJoPaTo**
Using the existing types in my own code is often helpful so they should be exported too

Also TypeScript seems to not emit files for .d.ts files so they are not shipped then → missing types on npm. I renamed them all to .ts and this issue is gone.

### CODE REVIEW

**Review by mshd — APPROVED** [review]
nice

**Comment by EdJoPaTo** [comment]
> When will the fix be merged to main branch?

Probably when people find the time to do it. A lot of open source happens because people have fun doing it in their free time. Asking for it will not speed up anything. It might only annoy people reducing their fun in doing it :upside_down_face: 

In the meantime:

```ts
// @ts-expect-error wait for fixed version of wikibase-sdk
```

**Comment by maxlath** [comment]
Thanks! Merged and published in `v9.0.5`

**Comment by EdJoPaTo** [comment]
this is awesome, I was able to replace all the uses of my wikibase-types library with v9.0.5

Guess I can deprecate it in favour of wikibase-sdk ✨

**Pull request merged**
